### PR TITLE
654 grb::set matrix to matrix broken in mixed domain

### LINKED ISSUE #241: grb::set matrix-to-matrix broken in mixed-domain
The primitive `grb::set( Matrix<D>&, const Matrix<T> )` contains a bug related to the cast of the values from T to D.

### PR DESCRIPTION
**Pull request by byjtew**
Closes #241 

- Removed redundancy in the `Compressed_Storage::copyFrom(...)` functions. The section in charge of copying the *row_index* and *col_start* arrays has been moved to an external local function called `copyCoordinatesFrom(...)`

- Merged the cast/no-cast `Compressed_Storage::copyFrom(...)` functions using `std::copy_n` rather than a for-loop/memcpy switch

### CODE REVIEW

File: include/graphblas/base/io.hpp [hunk 1]
```diff
@@ -1078,6 +1078,120 @@ namespace grb {
...
+		typename RIT2, typename CIT2, typename NIT2,
+		Backend backend
+	>
+	RC set(
+		Matrix< OutputType, backend, RIT1, CIT1, NIT1 > &A,
+		const Matrix< InputType, backend, RIT2, CIT2, NIT2 > &C,
+		const Phase &phase = EXECUTE
+	) noexcept {
+#ifndef NDEBUG
+		const bool should_not_call_base_matrix_set_copy_masked = false;
```
Comment (anyzelman) [inline include/graphblas/base/io.hpp]: `should_not_call_base_matrix_set_copy_masked` -> `should_not_call_base_matrix_set_copy` ?

File: include/graphblas/reference/compressed_storage.hpp [hunk 2]
```diff
@@ -502,21 +580,17 @@ namespace grb {
...
 				/**
-				 * Copies contents from a given Compressed_Storage.
+				 * Copies coordinates from a given Compressed_Storage, then fills the
+				 * values with the given identity.
 				 *
 				 * Performs no safety checking. Performs no (re-)allocations.
 				 *
-				 * @tparam use_id If set to <tt>true</tt>, use \a id instead of values in
-				 *                \a other.
-				 *
```
Comment (anyzelman) [inline include/graphblas/reference/compressed_storage.hpp]: Incorrect deletion?

File: include/graphblas/reference/compressed_storage.hpp [hunk 3]
```diff
@@ -502,21 +580,17 @@ namespace grb {
...
 				 * @param[in] other The container to copy from.
 				 * @param[in] nz    The number of nonzeroes in the \a other container.
 				 * @param[in] m     The index dimension of the \a other container.
 				 * @param[in] start The start position to copy from (inclusive).
 				 * @param[in] end   The end position to copy to (exclusive).
 				 * @param[in] id    A pointer to a value overriding those in \a other.
-				 *                  Will only be used if and only if \a use_id is set
-				 *                  <tt>true</tt>.
```
Comment (anyzelman) [inline include/graphblas/reference/compressed_storage.hpp]: incorrect deletion?

File: include/graphblas/reference/compressed_storage.hpp [hunk 4]
```diff
@@ -660,26 +692,12 @@ namespace grb {
...
-							assert( col_start[ chk ] <= col_start[ chk + 1 ] );
-						}
-#endif
-					}
+
+					copyCoordinatesFrom( *this, other, nz, m, k, end );
 				}
 
+
+
```
Comment (anyzelman) [inline include/graphblas/reference/compressed_storage.hpp]: Remove superfluous empty lines?

File: include/graphblas/reference/io.hpp [hunk 5]
```diff
@@ -969,27 +969,50 @@ namespace grb {
...
-			const InputType2 * __restrict__ id = nullptr
+			const Matrix< InputType, reference, RIT2, CIT2, NIT2 > &A,
+			const ValueType * __restrict__ id = nullptr
 		) noexcept {
 #ifdef _DEBUG
 			std::cout << "Called grb::set (matrices, reference), execute phase\n";
 #endif
+			if( A_is_mask ) {
+				assert( id != nullptr );
+			}
```
Comment (anyzelman) [inline include/graphblas/reference/io.hpp]: Maybe put this block in an `#ifndef NDEBUG`  ?

Comment (anyzelman) [reply include/graphblas/reference/io.hpp]: Also I tend to order dynamic checks (including asserts) until after the static checks -- in reality it doesn't matter much, but as a kind of style standard.

File: tests/unit/copyMixedDomainsMatrices.cpp [hunk 6]
```diff
@@ -0,0 +1,211 @@
...
+#include <vector>
+#include <numeric>
+#include <algorithm>
+
+#include <graphblas.hpp>
+
+
+using namespace grb;
+
+
```
Comment (anyzelman) [inline tests/unit/copyMixedDomainsMatrices.cpp:27]: superfluous empty line?

File: tests/unit/copyMixedDomainsMatrices.cpp [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
+		) {
+			std::cerr << "\t initialisation of A_int FAILED: rc is "
+				<< grb::toString( rc ) << "\n";
+			rc = FAILED;
+			return;
+		}
+	}
+
+
+
```
Comment (anyzelman) [inline tests/unit/copyMixedDomainsMatrices.cpp]: also here

File: tests/unit/copyMixedDomainsMatrices.cpp [hunk 8]
```diff
@@ -0,0 +1,211 @@
...
+	size_t in = 100;
+
+	// error checking
+	if( argc > 2 ) {
+		printUsage = true;
+	}
+	if( argc == 2 ) {
+		size_t read;
+		std::istringstream ss( argv[ 1 ] );
+		if( ! ( ss >> read ) ) {
```
Comment (anyzelman) [inline tests/unit/copyMixedDomainsMatrices.cpp]: no space after `!`

File: include/graphblas/reference/io.hpp [hunk 9]
```diff
@@ -969,27 +969,50 @@ namespace grb {
...
+			NO_CAST_ASSERT(
+				( !( descr & descriptors::no_casting ) ||
+				( std::is_same< NIT1, NIT2 >::value ) ),
+				"internal::grb::set", "called with non-matching value index types"
+			);
 			NO_CAST_ASSERT( ( !( descr & descriptors::no_casting ) ||
-				( A_is_mask && std::is_same< InputType2, OutputType >::value ) ),
+				( A_is_mask && std::is_same< ValueType, OutputType >::value ) ),
 				"internal::grb::set", "Called with non-matching value types"
 			);
```
Comment (anyzelman) [inline include/graphblas/reference/io.hpp]: Add a static assert that checks that ValueType can be cast into OutputType (if A_is_mask is false)?

File: include/graphblas/reference/compressed_storage.hpp [hunk 10]
```diff
@@ -1176,45 +1194,22 @@ namespace grb {
...
+					typename UnusedType = std::nullptr_t
 				>
 				void copyFrom(
-					const Compressed_Storage< InputType, IND, SIZE > &other,
+					const Compressed_Storage< InputType, InputIND, InputSIZE > &other,
 					const size_t nz, const size_t m, const size_t start, size_t end,
 					const UnusedType * __restrict__ = nullptr
 				) {
 					// the use_id template is meaningless in the case of pattern matrices, but
 					// is retained to keep the API the same as with the non-pattern case.
```
Comment (anyzelman) [inline include/graphblas/reference/compressed_storage.hpp]: add `(void) unusedValue;` (to prevent static code analysis warnings) and update the flagged comment with use_id->unusedValue

File: include/graphblas/reference/compressed_storage.hpp [hunk 11]
```diff
@@ -618,39 +678,11 @@ namespace grb {
...
-#endif
-						assert( k <= loop_end );
-						(void) std::memcpy(
-							row_index + k,
-							other.row_index + k,
-							(loop_end - k) * sizeof( IND )
-						);
+
+						GRB_UTIL_IGNORE_CLASS_MEMACCESS;
+						std::copy_n( other.values + k, loop_end - k, values + k );
```
Comment (anyzelman) [inline include/graphblas/reference/compressed_storage.hpp]: Two issues:
- should go into an OMP guard and set start, end initially also based on the thread ID?
- I prefer an explicit for-loop instead of `copy_n` because of the cross-domain casting that spawned the issue (better to have it explicit)

File: include/graphblas/reference/compressed_storage.hpp [hunk 12]
```diff
@@ -30,6 +30,84 @@ namespace grb {
...
+						input.col_start + k,
+						loop_end - k,
+						output.col_start + k
+					);
+	#ifndef NDEBUG
+					for( size_t chk = k; chk < loop_end - 1; ++chk ) {
+						assert( input.col_start[ chk ] <= input.col_start[ chk + 1 ] );
+						assert( output.col_start[ chk ] <= output.col_start[ chk + 1 ] );
+					}
+	#endif
```
Comment (anyzelman) [inline include/graphblas/reference/compressed_storage.hpp]: This block should execute in parallel (for the `reference_omp` backend)-- if intercepting at the indicated block, the usual OMP function may be used to cut the range k to loop_end statically.

If I read the static asserts in this file correctly, `copy_n` may also here perform casing, in which case it may be nicer to either disallow it (is it ever necessary to copy between mis-matching coordinate classes? I remember seeing static asserts that explicitly disallowed it elsewhere in this MR), or, alternatively, to write it explicitly in a for-loop.

Note that for parallelisation it doesn't matter -- if we have the thread-local start and end coordinates, each thread could in principle call `copy_n` (or do a for-loop).

I'm fine with either -- I think retaining the possibility of casting is more future-proof, so a slight bias towards that. Copy_n I would only retain if disallowing casting.

**Review by anyzelman — CHANGES_REQUESTED** [review]

File: include/graphblas/base/io.hpp (hunk 1 above)
Comment (byjtew) [reply include/graphblas/base/io.hpp:1126]:
```suggestion
		const bool should_not_call_base_matrix_set_copy = false;
```

File: include/graphblas/reference/compressed_storage.hpp (hunk 11 above)
Comment (byjtew) [reply include/graphblas/reference/compressed_storage.hpp]: Well since this whole logic is called within an already opened OMP region I am not sure it's a good idea. But I can switch to an `simd` for-loop

File: include/graphblas/reference/compressed_storage.hpp (hunk 12 above)
Comment (byjtew) [reply include/graphblas/reference/compressed_storage.hpp]: Same comment as above:
> Well since this whole logic is called within an already opened OMP region I am not sure it's a good idea. But I can switch to an `simd` for-loop

**Review by anyzelman — DISMISSED** [review]

**Comment by anyzelman** [comment]
Here is a question though: currently the `grb::set( matrix, mask, value );` does not take mask descriptors right?

I think there's good reason for not supporting `invert_mask`, because that implies a quadratic workload (in the size of the matrices), and seems only useful for cases where the mask matrix that is to be inverted has a number of nonzeroes that approaches the same quadratic bound-- i.e., it turns more into a dense computation that is typically best avoided.

However, we could support non-structural masks that inspect the mask-matrix' actual value, and if it compares false, not copy its coordinate into the output matrix. Since we copy row-by-row this should not be hard to implement. The current semantics would then be activated once more when passing the `descriptors::structural' in there. Would that be hard to add in @byjtew ?

**Comment by anyzelman** [comment]
I do note that in disagreement to what I wrote above, that the GraphBLAS C API does support mask inversion even in the matrix case.

**Comment by anyzelman** [comment]
Actually now also partially disagreeing with myself: it is still useful to invert a non-structural mask. We could forbid (static_assert) inverting a structural mask specifically maybe?

**Comment by anyzelman** [comment]
This one is ready to merge (after conflict resolution)

**Comment by anyzelman** [comment]
Kind of feel bad for not merging this earlier - a bunch of conflicts emerged meanwhile, now (hopefully) fixed. Also did a cursory code review and fixes due to the rebase. Running unit tests now to make sure nothing broke, then will continue review. I saw at least one TODO:

- [x] while I understand the intent of the `omp simd` pragmas, I don't believe they actually trigger at the moment. Can be re-written using the standard way for "auto"-vectorising applied everywhere else in ALP

**Review by anyzelman — APPROVED** [review]

**Comment by anyzelman** [comment]
Code review OK, GitHub CI OK. Waiting internal CI OK and manual unit test run with LPF OK before merge.

**Comment by anyzelman** [comment]
Concept release notes:

This MR fixes the behaviour of `grb::set( matrix, * )` by 1) correctly interpreting output masks and 2) fixes the behaviour of casting values from the input matrix value type to that of the output matrix.

This MR also
- adds a unit test for both fixes to guard against regressions;
- fixes / updates the base specification of `grb::set( matrix, * )`;
- allows for `grb::set( matrix, matrix[, scalar] )` to work for two matrices with different index / offset types;
- improves debug tracing for the reference `Compressed_Storage` class;
- includes minor code style fixes.

Thanks to Benjamin Lozes for initially identifying the issue and providing the fix!

**Comment by anyzelman** [comment]
Internal CI & internal unit tests (with LPF) OK; will merge
